=== FMIアプリケーション・プログラミング・インターフェース

このセクションでは、CプログラムからFMUの機能を実行するための共通インターフェース定義を記載しています。

なお、FMUには以下のような一般的な性質があります。

- 1つのインスタンスのFMI関数は、スレッドセーフである必要はありません。 +
_[例えば、FMUの1つのインスタンスの機能が複数のスレッドからアクセスされる場合。FMUを使用するマルチスレッド環境では、3.2.3項および4.2.4項で定義された関数の呼び出しシーケンスが使用されることを保証する必要があります。
FMU自身は、これをサポートするサービスを実装していません。]_

- FMI 関数は、他のプロセス/スレッドに影響するグローバル設定を変更してはいけません。
FMI 関数は、呼び出されたプロセス／スレッドの設定（浮動小数点制御レジスタなど）を変更することができます。ただし、これらの変更は、関数を終了する前、またはコールバック関数が呼び出される前に復元されます。 +
_[この特性により、異なるFMUインスタンスの関数を任意の順序で安全に呼び出すことができます。
さらに、関数が異なるプロセス/スレッドで呼び出されていれば、並行して呼び出すことができます。
FMI関数がCPUの浮動小数点制御ワードなどを変更した場合、関数が戻る前に以前の値に戻す必要があります。
x86 CPUの場合、浮動小数点制御ワードはfldcw命令で設定されます。
これは、「浮動小数点のゼロ除算」などの追加例外のスイッチを入れるために使用できます。
FMUは一時的に浮動小数点制御ワードを変更し、内部的に浮動小数点例外の通知を受けることができますが、それぞれのFMI関数が戻る前にフラグを復元し、浮動小数点ステータス・ワードをクリアする必要があります。]_


==== ヘッダーファイルと関数名の命名

FMUのインターフェースを定義する3つのヘッダーファイルが用意されています。
すべてのヘッダーファイルでは、C言語の関数や型の定義はすべて「[underline]#fumi2#」という接頭辞で始まるという規則が使われています。

- `fmi2TypesPlatform.h` +
には、関数の入力引数と出力引数の型定義が含まれています。
このヘッダファイルは，FMUとターゲットとなるシミュレータの両方で使用する必要があります。
ターゲットとなるシミュレータでヘッダファイルの定義が異なる場合（例えば、`**typedef double** fmi2Real`の代わりに`**typedef float** fmi2Real`）、[underline]#ターゲットとなるシミュレータ#で使用されているヘッダファイルを用いて[underline]#FMU#を[underline]#再コンパイル#する必要があります。
モデルがコンパイルされたヘッダファイルのプラットフォームは、ターゲットのシミュレータで次のように照会できます。
fmi2GetTypesPlatform` (セクション 2.1.4 参照)。 +
_[このヘッダーファイルでの定義の例: +
 `**typedef double** fmi2Real;` +
 ]_

- `fmi2FunctionTypes.h` +
には、FMUのすべての関数プロトタイプの `**typedef**` 定義が含まれています。
FMUを動的にロードする際には、これらの定義を使って、関数ポインタをそれぞれの関数定義にタイプキャストすることができます。
_[このヘッダーファイルでの定義の例: +
 `**typedef** fmi2Status fmi2SetTimeTYPE(fmi2Component, fmi2Real);` +
 ]_

- `fmi2Functions.h` +
には，シミュレーション環境でアクセス可能なFMUの関数プロトタイプが含まれており，2章，3章，4章で定義されています。
このヘッダファイルには，`fmi2TypesPlatform.h`と`fmi2Function.h`が含まれています。
モデルがコンパイルされたときのヘッダーファイルのバージョン番号です。ターゲットのシミュレータでは、`fmi2GetVersion` (セクション2.1.4参照)で確認できます。
_[このヘッダーファイルでの定義の例_ footnote:[MicrosoftとCygwinのコンパイラではFMI2_Export` は `pass:[__]declspec(dllexport)` として定義され、Gnu-Compilers では `FMI2_Export` は `pass:[__]attribute__ ( ( visibility("default") ) )` として定義され、ダイナミックローディングのために名前をエクスポートします。
それ以外は空の定義となります。]: +
_`FMI2_Export fmi2SetTimeTYPE fmi2SetTime;` +
]_

目標は、FMUのテキスト表現とバイナリ表現の両方をサポートし、1つの実行ファイルに複数のFMUが同時に存在する可能性があることです（例えば、FMU AがFMU Bを使用する場合など）。
これを可能にするためには、異なるFMUの関数名が異なるか、関数ポインタを使用する必要があります。
最初のバリエーションをサポートするために、FMUの出荷方法に依存する関数プレフィックスを使用して実際の関数名を構築するマクロが `fmi2Functions.h` で提供されています。
_[これらのマクロは、サポートされているコンパイラやインポートツールのプラットフォームの要件に合わせて、`fmi2Functions.h`のターゲット固有のバージョンで異なる定義をすることができます。]_

FMUのCファイルは、先頭に<fmiModelDescription><ModelExchange>`または<fmiModelDescription><CoSimulation>`で定義された`modelIdentifier`属性としての`FMI2_FUNCTION_PREFIX`の`define`を、末尾に`pass:[_]`を含めなければなりません（3.3.1項および4.3.1項参照）。

この`define`には、`#include "fumi2Functions.h"`を直接記述する必要があります。

通常、FMUの機能は以下のように使用されます。

[source, C]
----
// FMU is shipped with C source code, or with static link library
#define FMI2_FUNCTION_PREFIX MyModel_
#include "fmi2Functions.h"
< usage of the FMU functions >
----

[source, C]
----
// FMU is shipped with DLL/SharedObject
#include "fmi2Functions.h"
< usage of the FMU functions >
----

fmi2GetReal`と定義されている関数は、マクロによって以下のように関数名に変更されます。

- FMUにC言語のソースコードやスタティックリンクライブラリが付属している場合は: +
構築された関数名は `MyModel_fmi2GetReal` です。
つまり，関数名の前にはモデルの識別子と`pass:[_]`が付けられています．
したがって，シミュレーション環境では，実際の関数呼び出しのためのコードを生成することで，関連する関数名を構築することができます．
スタティックリンクライブラリの場合、ライブラリ名はWindowsではMyModel.lib、LinuxではlibMyModel.aとなり、`modelIdentifier`属性がライブラリ名として使用されます。

- FMUにDLL/SharedObjectが同梱されている場合: +
構築された関数名は `fmi2GetReal` であり、変更されていません。
_[これは、ソースコードのFMUが、関数名の構築にFMI2_FUNCTION_PREFIXを使用しないターゲット固有のバージョンの`fmi2Functions.h`を持つ場合に実現できます。]_
シミュレーション環境は、このライブラリを動的にロードし、FMI関数名を文字列として提供することで、関数シンボルを明示的にインポートします。
ライブラリの名前は、Windowsでは`MyModel.dll`、Linuxでは`MyModel.so`となり、つまり、`modelIdentifier`属性がライブラリ名として使われます。

_[FMUは、基本的に他のツールとの通信のみを含むように、オプションで出荷することができます（needsExecutionTool = true、4.3.1項参照）。
これは、特に共同シミュレーションタスクでよく見られます。
FMI 1.0では、関数名の前に常にモデル名が付いているため、モデルごとにDLL/共有オブジェクトを生成する必要があります。
FMI 2.0では、DLL/共有オブジェクトの場合、モデル名がプレフィックスとして使用されなくなったため、この状況が改善されました。
したがって、ツールカップリングの場合、1つのDLL/共有オブジェクトをすべてのモデルに使用することができます。
FMUがシミュレーション環境にインポートされる場合、これは通常、動的に実行され（FMU名に基づいて、シミュレーション環境の実行中に対応するFMUがロードされます）、モデル名がプレフィックスであるかどうかは問題ではありません。
]_

`modelIdentifier`は、C関数名のプレフィックスとして使用されるので、C関数名の制限を満たさなければなりません（文字、数字、アンダースコアのみが使用可能）。
_[例えば、`modelName = "A.B.C"`であれば、`modelIdentifier`は "A_B_C "となります。]_
modelIdentifier`は、ファイルシステムの名前としても使われます。ファイルシステムの名前としても使われるので、対象となるOSの制限を満たす必要があります。
基本的に、これは短くなければならないことを意味します。
例えば、WindowsのAPIでは、ファイルのフルパス名を260文字までしかサポートしていません。文字までしかサポートしていません（参照：http://msdn.microsoft.com/en-us/library/aa365247%28VS.85%29.aspx）。


==== プラットフォームに依存する定義 (fmi2TypesPlatform.h)

移植を容易にするため、関数のインターフェースにはC言語の型は使用していません。
しかし，このセクションではエイリアス型が定義されています。
このセクションのすべての定義は，ヘッダファイル `fmi2TypesPlatform.h` で提供されています。

`#define fmi2TypesPlatform "default"`

fmi2GetTypesPlatform`で問い合わせることができる定義です。
バイナリのコンパイルに使用するヘッダファイルを一意に識別するために使用されます。
_[以下の「デフォルト」定義は、ほとんどの一般的なプラットフォームに適しています。
すべてのバイナリFMUにこの「デフォルト」定義を使用することをお勧めします。
ソースコードFMUに限っては、場合によっては変更が有効なことがあります。]_:

----
fmi2Component           : 不透明なオブジェクトポインタ
fmi2ComponentEnvironment: 不透明なオブジェクトポインタ
fmi2FMUstate            : 不透明なオブジェクトポインタ
fmi2ValueReference      : 値のハンドル型
fmi2Real                : リアルデータ型
fmi2Integer             : 整数データ型
fmi2Boolean             : fmi2Trueおよびfmi2Falseで使用されるデータ型
fmi2Char                : 文字データ型（1文字の大きさ）
fmi2String              : fmi2Char文字のベクトルへのポインタ
                          (UTF-8エンコードのヌル終端文字列'\0')
fmi2Byte                : マシンの最小アドレス単位
                          (通常1バイト)
----

[source, C]
----
typedef void* fmi2Component;
----

これは、モデルの方程式を処理したり、それぞれのスレーブのコ・シミュレーションを処理するために必要な情報を含むFMU固有のデータ構造へのポインタです。
このデータ構造は、FMUを提供する環境によって実装されます。
言い換えれば、呼び出した環境はその内容を知らず、それを処理するコードはFMU生成環境が提供し、FMUと共に出荷されなければならないということです。

[source, C]
----
typedef void* fmi2ComponentEnvironment;
----

これは，FMUを呼び出すシミュレーション環境のデータ構造へのポインタです．
このポインタを使って，`modelDescription.xml`ファイルのデータ_[例えば、`valueReference`pass:[s]の変数名へのマッピング。]_をシミュレーション環境と`logger`関数（2.1.5項参照）の間で転送することができます．

[source, C]
----
typedef void* fmi2FMUstate;
----

FMUの内部状態を保存するデータ構造へのポインタで、実際の時間または前の時間の瞬間のFMUの内部状態を保存します。
これにより、前回のFMUの状態からシミュレーションを再開することができます（2.1.8項参照）。

[source, C]
----
typedef unsigned int fmi2ValueReference;
----

これは、モデルの(ベースタイプ)変数値へのハンドルです。
ハンドルとベースタイプ（`fmi2Real`など）は、変数の値を一意に識別します。
同じハンドルを持つ同じベースタイプの変数は、常に同一の値を持ちます。しかし、変数の定義の他の部分は異なる場合があります。 _[例えば、min/max属性]_.

レコードや配列などの構造化されたエンティティはすべて，`fmi2Real`や`fmi2Integer`などのスカラ値の集合に "フラット化 "されます．
fmi2ValueReference`はそのようなスカラの一つを参照します。
fmi2ValueReference`のコーディングは，FMUを生成した環境の "秘密 "です．
方程式のインターフェイスでは，このハンドルを介して変数にアクセスすることしかできません．
変数の具体的な情報を抽出するには、値のハンドルが定義されているモデル記述ファイルを読み込んだ使用環境に特有のものとなります。
以下のセクションの関数が間違った`fmi2ValueReference`の値で呼び出された場合は
_[例えば、`fmi2SetReal(...)`関数の呼び出しで定数を設定する場合などです]_,
その場合、この関数はエラー（`fmi2Status = fmi2Error`、セクション2.1.3参照）で返さなければなりません。

[source, C]
----
typedef double fmi2Real ; // Data type for floating point real numbers
typedef int fmi2Integer;  // Data type for signed integer numbers
typedef int fmi2Boolean;  // Data type for Boolean numbers
                          // (only two values: fmi2False, fmi2True)
typedef char fmi2Char;    // Data type for one character
typedef const fmi2Char* fmi2String; // Data type for character strings
                                    // ('\0' terminated, UTF8 encoded)
typedef char fmi2Byte;    // Data type for the smallest addressable
                          // unit, typically one byte
#define fmi2True 1
#define fmi2False 0
----

これらは、C関数のインターフェースで使用される基本的なデータ型です。
将来のバージョンのインターフェースでは、さらに多くのデータ型が追加される可能性があります。柔軟性を保つために，特に組み込みシステムや高性能コンピュータのために，正確なデータ型や数値のワード長は標準化されていません．
代わりに、正確な定義（言い換えれば、ヘッダファイル `fmi2TypesPlatform.h`）は、FMUが使用される環境によって提供されます。ほとんどの場合、上記の定義が使われます。
ターゲット環境の定義が異なり、FMUがバイナリ形式で配布されている場合は、このターゲットヘッダーファイルを用いて新たにコンパイルおよびリンクする必要があります。

fmi2String`変数がFMI関数の[underline]#input#引数として渡され、FMUがその文字列を後で使用する必要がある場合、FMI関数は関数が戻る前にその文字列をコピーし、FMUの内部メモリに保存しなければなりません。

FMI関数の[underline]#output#引数として`fmi2String`変数が渡され、その文字列がターゲット環境で使用される場合、ターゲット環境は（ポインタだけでなく）文字列全体をコピーする必要があります。
この文字列のメモリは、いずれかのFMIインターフェース関数の次の呼び出しによって解放される可能性があります。(文字列のメモリは、再利用される単なるバッファの場合もあります)。


==== 関数が返すステータス
このセクションでは、すべての関数が返す `status` フラグ (ファイル `fmi2FunctionTypes.h` で定義されている `fmi2Status` 型の列挙型) を定義します。ファイル`fmi2FunctionTypes.h`で定義されている`fmi2Status`型の列挙）を定義します。


[source, C]
----
typedef enum { fmi2OK,
               fmi2Warning,
               fmi2Discard,
               fmi2Error,
               fmi2Fatal,
               fmi2Pending } fmi2Status;
----

関数が返すステータス。
ステータスの意味は以下の通りです。

- `fmi2OK` - すべて順調

- `fmi2Warning` - 完全に正しくありませんが、計算は続行できます。
モデルの中では，関数`logger`が呼び出されており（下記参照），この関数が用意した情報メッセージをユーザに表示したことが予想されます。

- `fmi2Discard` - この戻り値は、対応する関数で明示的に定義されている場合のみ可能です footnote:[関数 `fmi2SetXXX` は通常、計算を行わず、渡された値を内部バッファに格納するだけです。
実際の計算は`fmi2GetXXX`関数が行います。
しかし、`fmi2SetXXX`関数は、入力された引数が有効範囲内にあるかどうかをチェックすることができます。
そうでない場合、これらの関数は `fmi2Discard` で返すことができます。]:
(ModelExchange: `fmi2SetReal`, `fmi2SetInteger`, `fmi2SetBoolean`, `fmi2SetString`,
`fmi2SetContinuousStates`, `fmi2GetReal`, `fmi2GetDerivatives`,
`fmi2GetContinuousStates`, `fmi2GetEventIndicators`;
CoSimulation: `fmi2SetReal`, `fmi2SetInteger`, `fmi2SetBoolean`, `fmi2SetString`, `fmi2DoStep`,
`fmiGetXXXStatus` ): +
「モデル交換」の場合：モデルの反復ソルバーが収束しなかった場合や、モデルの方程式を再度評価する場合など、ステップサイズを小さくして実行することが推奨されます。モデルの反復ソルバーが収束しなかった場合や、関数が領域外にある場合（例：`sqrt(<負の数>)`）などには 例えば、モデル内の反復ソルバーが収束しなかった場合や、関数がその領域外にある場合（例：`sqrt(<負の数>)`）などです。
これができない場合は、シミュレーションを終了しなければなりません。 +
「co-simulation」の場合：スレーブが必要なステータス情報を返せなかった場合も、`fmi2Discard`を返します。ステータス情報を返すことができない場合にも返されます。
マスターは、シミュレーションの実行を継続できるかどうかを判断する必要があります。 +
いずれの場合も、FMUでは関数`logger`が呼び出されており（下記参照）、FMUがデバッグモード（`loggingOn = fmi2True`）で呼び出された場合には、この関数が用意された情報メッセージをユーザーに表示していることが予想されます。
それ以外の場合は、`logger`はメッセージを表示してはいけません。

- `fmi2Error` - FMUにエラーが発生しました。
このFMUインスタンスでは、シミュレーションを続行できません。
いずれかの関数が `fmi2Error` を返した場合は、`fmi2SetFMUstate` を呼び出して、以前に保存した FMU の状態からシミュレーションを再開することができます。
これは、ケイパビリティフラグの `canGetAndSetFMUstate` が真であり、`fmi2GetFMUstate` が以前にエラーにならない状態で呼び出されていた場合に実行できます。
footnote:[通常、`fmi2Error`は「ディスクが一杯です」などの数字にならない理由で返されます。
fmi2SetFMUstate`で定義された最後の一貫した状態でシミュレーションを続行することができます。]。+
特に他のFMUインスタンスは影響を受けません。
FMUでは、関数`logger`が呼び出されており（下記参照）、この関数が用意された情報メッセージをユーザーに表示していることが予想されます。

- `fmi2Fatal` - すべての FMU インスタンスでモデル計算が修復不可能なほど破損します。
_[例えば、fmi関数の実行中に、アクセス違反や整数のゼロ除算などのランタイム例外が発生したため]_です。
FMUで関数`logger`が呼び出され（下記参照）、この関数が用意した情報メッセージをユーザーに表示したことが予想されます。
FMUのどのインスタンスに対しても、他の関数を呼び出すことはできません。

- `fmi2Pending` - このステータスは、スレーブが非同期で関数を実行した場合に、コ・シミュレーションのインターフェースからのみ返されます。
つまり，スレーブが計算を開始してもすぐに戻ってくるということです．
マスターはスレーブが計算を終了したかどうかを判断するために、`fmi2GetStatus(..., fmi2DoStepStatus)`を呼び出す必要があります。
fmi2DoStep`と`fmi2GetStatus`(4.2.3項参照)でのみ返すことができます。


==== ヘッダーファイルのプラットフォームとバージョン番号の照会

このセクションでは、関数のコンパイルに使用されたヘッダーファイルの情報を照会するために、関数を文書化します。

[source, C]
----
const char* fmi2GetTypesPlatform(void);
----

FMUの機能のコンパイルに用いられるヘッダファイル `fmi2TypesPlatform.h` を一意に識別するための文字列を返します。
この関数は，このヘッダファイルで定義されている `fmi2TypesPlatform` で指定される静的な文字列へのポインタを返します．
本仕様書に記載されている標準的なヘッダファイルでは，`fmi2TypesPlatform`が`default`に設定されています（したがって，この関数は通常`default`を返します）．

[source, C]
----
const char* fmi2GetVersion(void);
----

FMUの関数をコンパイルする際に使用したヘッダファイル `fmi2Functions.h` のバージョンを返します。
この関数は、このヘッダファイルで定義されている `fmiVersion` を返します。
本仕様書に記載されている標準的なヘッダファイルのバージョンは `"2.0"` です（したがって、この関数は通常 `"2.0"` を返します）。


==== FMUインスタンスの作成、破棄、ログの記録

ここでは、FMUのインスタンス化、破壊、ロギングに対応する機能について説明します。

[source, C]
----
fmi2Component fmi2Instantiate(fmi2String  instanceName,
                              fmi2Type    fmuType,
                              fmi2String fmuGUID,
                              fmi2String fmuResourceLocation,
                              const fmi2CallbackFunctions* functions,
                              fmi2Boolean visible,
                              fmi2Boolean loggingOn);
----

[source, C]
----
typedef enum {fmi2ModelExchange,
              fmi2CoSimulation
             }fmi2Type;
----

この関数は，FMU の新しいインスタンスを返します。
もし，NULLポインタが返された場合には，インスタンスの生成に失敗したことになります．
この場合，`functions->logger` が呼ばれ，その理由に関する詳細な情報が表示されます．
FMUは何度でもインスタンスを作成することができます（ケイパビリティフラグ`canBeInstantiatedOnlyOncePerProcess = false`があれば）。

以下の関数を呼び出す前に、この関数が正常に呼び出される必要があります。
共同シミュレーションの場合、この関数の呼び出しは、シミュレーションの実行を開始する前に必要なスレーブのすべてのアクションを実行する必要があります（たとえば、モデルファイルの読み込み、コンパイルなど）。

引数 `instanceName` は、FMUインスタンスの一意の識別子です。
これは、例えば、`fmi2XXX`関数のいずれかによって生成されたエラーまたは情報メッセージの中で、インスタンスの名前を付けるために使用されます。
また、この文字列は空であってはなりません（言い換えれば、少なくとも1つの文字が空白であってはなりません）。
_[1つのFMUのみをシミュレートする場合、instanceName属性として`modelName`またはXMLスキーマ`fmiModelDescription`の`<ModelExchange/CoSimulation modelIdentifier="...">`が使用されるかもしれません]_。

引数 `fmuType` は、FMUのタイプを定義します。:

- = `fmi2ModelExchange`: FMUの初期化とイベント;
連続したシステムのイベント間シミュレーションは、環境からの外部インテグレータを用いて 環境からの外部インテグレーターを用いて行われます（セクション3参照）。
- = `fmi2CoSimulation`: コ・シミュレーションのためのブラックボックス・インターフェース（セクション4参照）。

引数 `fmuGUID` は，`modelDescription.xml` ファイル（2.3節参照）がFMUのCコードと互換性があるかどうかを確認するために使用します．
これは、XMLファイルのベンダー固有のグローバルに一意な識別子です（例えば、XMLファイルに格納されている関連情報の「フィンガープリント」です）。
これは、XMLファイルの属性 "guid"（2.2.1項参照）として格納されており、`fmi2Instantiate`関数の引数`fmuGUID`に渡す必要があります。
これは，`fmi2Instantiate`関数の内部に格納されているものと同一でなければなりません．
さもなければ、C言語のコードとFMUのXMLファイルの整合性が取れません。
この引数はNULLではありません。

引数 `fmuResourceLocation` は、次の構文によるURIです。
http://datatracker.ietf.org/doc/rfc3986/[IETF RFC3986]の構文に従ったURIです。FMUアーカイブを解凍した際の`resources`ディレクトリへの位置を示すURIです。
以下のスキームは、FMUによって理解されなければなりません。:

- 必須項目です。"file "の絶対パス（オーソリティコンポーネントを含む、または含まない）。
- 任意："http"、"https"、"ftp"
- 予約済みです。FMI for PLM のための "fumi2" です。

_[例 FMUを "C:temp\MyFMU "というディレクトリに解凍した場合、fmuResourceLocation = "file:///C:/temp/MyFMU/resources "または "file:/C:/temp/MyFMU/resources "となります。
関数 `fmi2Instantiate` は、このディレクトリから、FMUが使用するマップやテーブルなど、必要なリソースをすべて読み込むことができます。]_

引数 `functions` は、環境からのリソースを利用するために、FMUの機能から使用するコールバック関数を提供します（下記のタイプ `fmi2CallbackFunctions` を参照）。

引数 `visible = fmi2False` は、ユーザーとのインタラクションを最小限に抑えることを定義しています（アプリケーションウィンドウがない、プロットがない、アニメーションがない、など）。
言い換えれば，FMUはバッチモードで実行されます．
Visible = fmi2True`の場合、FMUはインタラクティブモードで実行され、FMUはシミュレーション/インスタンス化/初期化の開始を明示的に確認する必要があるかもしれません（確認はノンブロッキングです）。

If `loggingOn = fmi2True`, デバッグログが有効になります。 +
If `loggingOn = fmi2False`, デバッグログが無効になります。

_[FMUは、この引数に従って、デバッグに役立つ`LogCategories`を有効／無効にします。
FMUがどの`LogCategories`を設定するかは未設定です。]_

[source, C]
----
typedef struct {
     void  (*logger)(fmi2ComponentEnvironment componentEnvironment,
                          fmi2String instanceName,
                          fmi2Status status,
                          fmi2String category,
                          fmi2String message, ...);
     void* (*allocateMemory)(size_t nobj, size_t size);
     void  (*freeMemory)    (void* obj);
     void (*stepFinished)   (fmi2ComponentEnvironment componentEnvironment,
                             fmi2Status status);
     fmi2ComponentEnvironment componentEnvironment;
} fmi2CallbackFunctions;
----

この構造体には、FMUが使用するために環境が提供する関数へのポインタが含まれています。
これらの関数を `fmi2Instantiate(...)` と `fmi2Terminate(...)` の間で変更することはできません。
さらに、`logger`関数が環境からのデータを利用できるように、`valueReference`を文字列にマッピングするなど、`logger`関数に渡す必要のある環境へのポインタ（componentEnvironment）が提供されます。
万が一、`fmi2Component`が`logger`でも必要になる場合は、引数componentEnvironment`を介して渡す必要があります。
引数 `componentEnvironment` には null ポインタを指定できます。

componentEnvironment` ポインタは、`stepFinished(...)` 関数にも渡されます。これは、`stepFinished(...)` を呼び出したスレーブを特定するための効率的な方法を環境が提供するためです。

デフォルトの `fmi2FunctionTypes.h` ファイルでは．使い方を簡単にするために、関数定義の型定義があります。これは規範的ではありません。
関数の意味は次のとおりです。:

関数*logger*:
FMUによって呼び出される関数へのポインタ _[通常、`fmi2XXX`関数が希望通りに動作しない場合]_です。
status = fmi2OK`の場合、メッセージは純粋な情報メッセージです。
instanceName` はこの関数を呼び出した FMU インスタンスの名前です。
category` はメッセージのカテゴリーです。

`category`の許容値は、`modelDescription.xml`ファイルの<fmiModelDescription><LogCategories>`という要素で定義されています(2.2.4項参照)。
logger` は、`fmi2SetDebugLogging` (下記参照) の呼び出し、または `fmi2Instantiate` の `loggingOn = fmi2True` によって有効になったログカテゴリに対してのみ呼び出す必要があります。
FMUがログカテゴリを定義していない場合、`category`は`NULL`でなければなりません。
引数の `message` は、ログに記録するメッセージを含む文字列です。
改行を含んでもかまいませんが、最後に改行があってはいけませんし、関数 `printn` と同じ方法、同じフォーマット制御で提供されます。C標準ライブラリの関数`printf`と同じ方法、同じフォーマット制御で提供されます。+
_[通常、この関数はメッセージを印刷し、オプションでログファイルに保存します]_。

FMUから`logger`に渡されたすべての文字列値の引数は、関数`logger`が戻った後、FMUによって直接解放されることがあります。
_[そのため、シミュレーション環境では、後でこれらの文字列にアクセスする必要がある場合、これらの文字列のコピーを作成する必要があります]_。+

ここで，<Type>は`fmi2Real`の "r"，`fmi2Integer`の "i"，`fmi2Boolean`の "b"，`fmi2String`の "s "です．
「i "は`fmi2Integer`、"b "は`fmi2Boolean`、"s "は`fmi2String`となります。
文字 `pass:[#]` をメッセージに含める場合は、その前に `pass:[#]` を付ける必要があります。
文字`pass:[#]`がメッセージに含まれる場合は、`pass:[#]`を前置しなければならないので、`#`はエスケープ文字となります。
_[例:_ +

_A message of the form "\#r1365# must be larger than zero (used in IO channel ##4)"_ +
_might be changed by the `logger` function to_ +
_`"body.m must be larger than zero (used in IO channel #4)"`_ +
_if `"body.m"` is the name of the `fmi2Real` variable with `fmi2ValueReference = 1365`.]_

関数 *allocateMemory* です。+
メモリを割り当てる必要がある場合に FMU で呼び出される関数へのポインタです。
<fmiModelDescription><ModelExchange / CoSimulation>`の属性`canNotUseMemoryManagementFunctions = true`の場合、関数`allocateMemory`はFMUで使用されません。
とすると、FMUでは関数`allocateMemory`は使用されず、ボイドポインタを提供することができます。
この属性の値が `false` (これがデフォルトです) の場合、FMU は `mallocateMemory` を使用してはいけません。
FMU は `malloc` や `calloc` などのメモリ割り当て関数を使用してはいけません。
理由の一つは、ターゲットマシンの組み込みシステムでは、これらの関数が利用できない可能性があるからです。
もう一つの理由は，環境が最適化された，あるいは特殊なメモリ割り当て関数を持っている可能性があるからです．
`allocateMemory` は，`nobj` オブジェクトのベクトルを格納する領域へのポインタを返します．
要求が満たされない場合には，サイズ `size` または `NULL` のそれぞれの `nobj` オブジェクトのベクトルの領域へのポインタを返します．
領域は0バイトに初期化されます_[(C標準ライブラリの`calloc`を使用するのが簡単な実装です)]_。

関数 *freeMemory* です。+
allocateMemory` で確保されたメモリを解放する際に、FMU で呼び出さなければならない関数へのポインタを指定します。
入力引数 `obj` に null ポインタが指定された場合、この関数は何も行いません。
この関数は何もしません_[(簡単な実装としては、C標準ライブラリのfreeを使用します。
ANSI C89とC99では、ヌルポインタの処理はここで定義されているものと同じです）]_.
<fmiModelDescription><ModelExchange / CoSimulation>`の属性`canNotUseMemoryManagementFunctions = true`の場合、関数`freeMemory`は何もしません。
の属性 `canNotUseMemoryManagementFunctions = true` の場合、関数 `freeMemory` は FMU で使用されず、ヌルポインターを提供することができます。

関数 *stepFinished* です。+
オプションのコールバック関数で、Co-シミュレーションスレーブの通信ステップの計算が終了したかどうかを通知します。
null ポインタを指定することもできます。
この場合、マスターは `fmiGetStatus(...)` を使って `fmi2DoStep` の状態を問い合わせる必要があります。
関数へのポインタが指定された場合は、通信ステップが完了した後にFMUがその関数を呼び出す必要があります。

_[注：FMI 3.0では、メモリコールバック関数は削除されました。これは、意図された用途が実現されず、実装に問題が生じることが多かったためです。
FMI 2.0.2の新機能：メモリコールバック関数の使用は推奨されません。]_

[source, C]
----
void fmi2FreeInstance(fmi2Component c);
----

与えられたインスタンスを破棄し、ロードされたモデルをアンロードします。
そして，FMUインタフェースの関数によって割り当てられたメモリやその他のリソースをすべて解放します。
c` に null ポインタが指定された場合、その関数の呼び出しは無視されます（効果がありません）。


[source, C]
----
fmi2Status fmi2SetDebugLogging(fmi2Component c, fmi2Boolean loggingOn,
                               size_t nCategories,
                               const fmi2String categories[]);
----
この関数は、FMUがloggerコールバック関数を介して出力するデバッグロギングを制御します。

loggingOn == fmi2True`の場合、`categories`で指定されたログカテゴリーに対してデバッグロギングが有効になり、そうでない場合は無効になります。
nCategories` は、引数 `categories` の長さを定義します。
nCategories == 0` の場合、`loggingOn` はすべてのログカテゴリに適用され、categories の値は未定義です。
categories` の許容値は、`modelDescription.xml` ファイルの要素 `<LogCategories>` で定義されます（2.2.4 節参照）。

==== Initialization, Termination, and Resetting an FMU

This section documents functions that deal with initialization, termination, and resetting of an FMU.

[source, C]
----
fmi2Status fmi2SetupExperiment(fmi2Component c,
                               fmi2Boolean   toleranceDefined,
                               fmi2Real      tolerance,
                               fmi2Real      startTime,
                               fmi2Boolean   stopTimeDefined,
                               fmi2Real      stopTime);
----

FMU に実験の設定を通知します。
この関数は、`fmi2Instantiate`の後、`fmi2EnterInitializationMode`が呼ばれる前に呼ばれなければなりません。
引数の `toleranceDefined` と `tolerance` は FMU のタイプに依存します。

[role=second-indented]
*fmuType = fmi2ModelExchange*: +
toleranceDefined = fmi2True`であれば、モデルは数値積分スキームで呼び出されます。
ステップサイズは、誤差の推定に「許容範囲」を使用して制御されます（通常は相対的な「許容範囲」として）。
このような場合、モデル内部で使用されるすべての数値アルゴリズム（例えば、非線形代数方程式の解
このような場合、モデル内部で使用されるすべての数値アルゴリズム（例えば、非線形代数方程式を解くため）は、適切な小さい相対的な許容範囲の誤差推定で動作する必要があります。

[role=second-indented]
*fmuType = fmi2CoSimulation*: +
toleranceDefined = fmi2True`とすると，スレーブの通信間隔を誤差評価で制御することになります。
スレーブが可変ステップサイズの数値積分器を使用していて、誤差を推定する場合は、内部積分器の誤差推定に`tolerance`を使用することをお勧めします。
(通常は相対的な許容値)を使用することをお勧めします。+
コ・シミュレーション用のFMUでは、この引数を無視することがある。

引数 `startTime` と `stopTime` は、モデルが与えられた境界内で有効かどうかをチェックしたり、結果を保存するために必要なメモリを割り当てるために使用することができます。
引数 `startTime` は独立変数の固定された初期値である。
footnote:[fmiModelDescription.xml`ファイルで`causality = "independent"`と定義されている変数です。]
value _[独立変数が`time`の場合、`startTime`は初期化の開始時間です。]_.
stopTimeDefined = fmi2True`の場合、`stopTime`は定義された独立変数の最終値であり[独立変数が`time`の場合、`stopTime`はシミュレーションの停止時間]、環境が`stopTime`を超えて計算しようとすると、FMUは`fmi2Status = fmi2Error`を返さなければなりません。
 stopTimeDefined = fmi2False`であれば、独立変数の最終値は定義されず、引数`stopTime`は意味を持ちません。


[source, C]
----
fmi2Status fmi2EnterInitializationMode(fmi2Component c);
----

FMUに初期化モードに入ることを通知します。
この関数を呼び出す前に、`<ScalarVariable initial = exact` または `approx>` という属性を持つすべての変数を `fmi2SetXXX` 関数で設定することができる（`ScalarVariable` 属性はモデル記述ファイルで定義されている。
fmi2SetXXX`関数で設定することができます（`ScalarVariable`属性はモデル記述ファイルで定義されています、2.2.7項参照）。
それ以外の変数を設定することはできません。
さらに，`fmi2EnterInitializationMode`を呼び出す前に，`fmi2SetupExperiment`を少なくとも一度は呼び出さなければ，`startTime`が定義されません．

[source, C]
----
fmi2Status fmi2ExitInitializationMode(fmi2Component c);
----

FMUに初期化モードの終了を通知します。
fmuType = fmi2ModelExchange`の場合、この関数はすべての初期化方程式をオフにし、FMUは暗黙のうちにイベントモードに入ります。つまり、すべての連続時間およびアクティブな離散時間方程式が利用可能になります。

[source, C]
----
fmi2Status fmi2Terminate(fmi2Component c);
----

シミュレーションの実行が終了したことをFMUに通知します。
この関数を呼び出した後、すべての変数の最終値は `fmi2GetXXX(...)` 関数で問い合わせることができます。
fmi2Error`や`fmi2Fatal`のステータスフラグを持つ関数の後にこの関数を呼び出すことはできません。

[source, C]
----
fmi2Status fmi2Reset(fmi2Component c);
----

シミュレーションの実行後に環境から呼び出され、FMUをリセットします。
FMUは、`fmi2Instantiate`が呼ばれたときと同じ状態になります。
すべての変数はデフォルト値になります．
新しい実行を開始する前に、`fmi2SetupExperiment`と`fmi2EnterInitializationMode`を呼び出す必要があります。

==== Getting and Setting Variable Values

FMUのすべての変数値は、「値参照」と呼ばれる変数ハンドルで識別されます。
このハンドルは `modelDescription.xml` ファイルの中で定義されています（要素 `ScalarVariable` の中の属性 `valueReference` として）。
要素 `valueReference` はすべての変数で一意ではないかもしれません。
同じ基本データ型（`fmi2Real`など）の2つ以上の変数が同じ`valueReference`を持つ場合、それらは同一の値を持ちますが、変数定義の他の部分は異なる可能性があります。
_[例えば、min/max属性]_.

modelDescription.xml`ファイルで定義されている変数の実際の値は，以下の関数を使って`fmi2EnterInitializationMode`を呼び出した後に問い合わせることができます．

[source, C]
----
fmi2Status fmi2GetReal   (fmi2Component c, const fmi2ValueReference vr[],
                          size_t nvr, fmi2Real value[]);
fmi2Status fmi2GetInteger(fmi2Component c, const fmi2ValueReference vr[],
                          size_t nvr, fmi2Integer value[]);
fmi2Status fmi2GetBoolean(fmi2Component c, const fmi2ValueReference vr[],
                          size_t nvr, fmi2Boolean value[]);
fmi2Status fmi2GetString (fmi2Component c, const fmi2ValueReference vr[],
                          size_t nvr, fmi2String value[]);
----

[role=indented2]
変数の参照先を指定して、変数の実際の値を取得することができます。
_[これらの関数は，モデルが他のモデルと接続されている場合に，出力変数の実際の値を得るために特に使用されます．
状態導関数も`ScalarVariable`pass:[s]なので，状態導関数の値を得ることができます．
これはFMU同士を接続する際に便利です。
さらに，`modelDescription.xml`ファイルで定義されたすべての変数の実際の値は，実際に定義された時間の瞬間に決定することができます（2.2.7節参照）．]_

[role=indented2]
- 引数の`vr`は、問い合わせを行う変数を定義する`nvr`の値ハンドルのベクトルです。
- 引数の `value` は、これらの変数の実際の値を持つベクトルです。
- fmi2GetString` が返す文字列は、ターゲット環境でコピーする必要があります。なぜなら、これらの文字列に割り当てられたメモリは、次に fmi2 インターフェース関数が呼び出されたときに解放されたり、再利用される内部の文字列バッファであったりする可能性があるからです。
- ModelExchangeでは、`fmi2Status = fmi2Discard`は、`fmi2GetReal`でのみ可能で、`fmi2GetInteger`、`fmi2GetBoolean`、`fmi2GetString`では不可能です。
なぜなら、これらは離散時間変数であり、その値はイベントの瞬間にしか変化しないため、`fmi2Discard`は意味をなさないからです。

また、以下の機能を使って、[underline]#特定の#変数の値を特定の瞬間に[underline]#設定する#ことも可能です。

[source, C]
----
fmi2Status fmi2SetReal   (fmi2Component c, const fmi2ValueReference vr[],
                          size_t nvr, const fmi2Real value[]);
fmi2Status fmi2SetInteger(fmi2Component c, const fmi2ValueReference vr[],
                          size_t nvr, const fmi2Integer value[]);
fmi2Status fmi2SetBoolean(fmi2Component c, const fmi2ValueReference vr[],
                          size_t nvr, const fmi2Boolean value[]);
fmi2Status fmi2SetString (fmi2Component c, const fmi2ValueReference vr[],
                          size_t nvr, const fmi2String value[]);
----

[role=indented2]
パラメータ、入力、開始値を設定し、これらの変数に依存する変数のキャッシングを再初期化します (どのタイプの変数 `fmi2SetXXX` を呼び出すことができるかの正確なルールについては、2.2.7節を参照してください。また、ModelExchangeの場合は3.2.3節、CoSimulationの場合は4.2.4節も参照してください)。

[role=indented2]
- 引数 `vr` は、設定すべき変数を定義する `nvr` 値ハンドルのベクトルです。
- 引数の `value` は、これらの変数の実際の値を持つベクトルです。
- fmi2SetString`に引数として渡された全ての文字列は、この関数内でコピーしなければなりません。なぜなら、この関数が戻ってきたときに文字列の寿命が保証されていないからです。
- なお、`fmi2SetXXX`関数では、`fmi2Status = fmi2Discard`が可能です。

コ・シミュレーションFMUでは、4.2.1項で、補間を可能にするために、時間に対する変数の微分を設定したり、問い合わせたりする追加関数が定義されている。

[#GetSetCompleteFMUState]
==== FMU Complete Stateの取得と設定

FMUは、シミュレーションを継続するために必要なすべての値で構成される内部状態を持っています。
この内部状態は、特に、連続時間状態の値、反復変数、パラメータ値、入力値、遅延バッファ、ファイル識別子、FMU内部のステータス情報で構成されています。
このセクションの機能により、FMUの内部状態をコピーし、このコピーへのポインタを環境に返すことができます。
コピーされたFMU状態を実際のFMU状態として設定し、そこからシミュレーションを継続することができます。

_[本機能の使用例:_

_コ・シミュレーション・マスター・アルゴリズムの可変ステップ・サイズ制御（通信ステップを受け付けるごとにFMUの状態を取得する。
通信ステップごとにFMU状態を取得する。
後続のステップが受け入れられなかった場合、このFMU状態から協調シミュレーションを再開する）。)_

_非線形カルマンフィルターの場合（初期化の直前にFMUの状態を取得します。
サンプル期間ごとに、測定値に基づいてカルマンフィルタアルゴリズムから新しい連続状態を設定する。
次のサンプルの瞬間まで積分し、カルマンフィルターアルゴリズムで使用された予測連続状態を、新しい連続状態を設定するための基礎として照会する）。)_

_非線形モデル予測制御の場合（初期化の直前にFMUの状態を取得する。
サンプル期間ごとにオブザーバーから新しい連続状態を設定して初期化し、初期化後のFMU状態を取得する。
この状態から、初期化後にオプティマイザが提案する新しい入力信号で再スタートするシミュレーションを多数行う）。)]_

さらに、FMUの状態をシリアル化し、バイトベクターでコピーすることができる:
_[これは、例えば、高価な定常状態の初期化を行うために使用することができます。受信したFMUの状態をバイトベクターにコピーして、このベクターをファイルに保存します。
必要に応じて、ファイルからバイトベクターをロードし、デシリアライズすることで
ファイルから読み込んでデシリアライズし、このFMUの状態からシミュレーションを再開することができます。つまり、定常状態の初期化からシミュレーションを再開することができます。]_

[source, C]
----
fmi2Status fmi2GetFMUstate (fmi2Component c, fmi2FMUstate* FMUstate);
fmi2Status fmi2SetFMUstate (fmi2Component c, fmi2FMUstate  FMUstate);
fmi2Status fmi2FreeFMUstate(fmi2Component c, fmi2FMUstate* FMUstate);
----

fmi2GetFMUstate`は内部のFMUの状態のコピーを作成し、そのコピーへのポインタ(`FMUstate`)を返します。
エントリで `*FMUstate == NULL` となった場合は、新たな割り当てが必要です。
FMUstate != NULL` の場合、`*FMUstate` は以前に返された `FMUstate` を指しており、それ以降は変更されていません。
特に、`fmi2FreeFMUstate`はこの`FMUstate`を引数にして呼び出されていません。
_[関数 `fmi2GetFMUstate` は通常、この `FMUstate` のメモリを再利用します。この場合、同じポインタを返しますが、実際の `FMUstate` を返します。]_

fmi2SetFMUstate`では、以前にコピーした`FMUstate`の内容を戻して、実際の新しいFMUステートとして使用します。
コピーされた`FMUstate`はまだ存在します。

fmi2FreeFMUstate`は、この`FMUstate`に対して`fmi2GetFMUstate`コールで割り当てられたすべてのメモリやその他のリソースを解放します。
この関数の入力引数には、解放する`FMUstate`を指定します。
ヌルポインターが指定された場合、その呼び出しは無視されます。
この関数は、引数 `FMUstate` に null ポインタを返します。

これらの関数がFMUでサポートされるのは、`<fmiModelDescription> <ModelExchange / CoSimulation> `のオプションのケイパビリティフラグ`canGetAndSetFMUstate`がXMLファイルで明示的に`true`に設定されている場合のみです（セクション3.3.1および4.3.1を参照）。
が明示的にtrueに設定されている場合のみサポートされます。

[source, C]
----
mi2Status fmi2SerializedFMUstateSize(fmi2Component c, fmi2FMUstate FMUstate,
                                     size_t *size);
fmi2Status fmi2SerializeFMUstate    (fmi2Component c, fmi2FMUstate FMUstate,
                                     fmi2Byte serializedState[], size_t size);
fmi2Status fmi2DeSerializeFMUstate  (fmi2Component c,
                                     const fmi2Byte serializedState[],
                                     size_t size, fmi2FMUstate* FMUstate);
----

fmi2SerializedFMUstateSize`は、`FMUstate`を格納できるように、バイトベクトルの`サイズ`を返します。
この情報をもとに、環境は必要な長さ `size` の `fmi2Byte` ベクトルを割り当てる必要があります。

fmi2SerializeFMUstate`は、ポインタ`FMUstate`で参照されるデータをシリアライズして、環境で提供される長さ`size`のバイトベクトル`serializedState`にコピーします。

fmi2DeSerializeFMUstate`は、長さ`size`のバイトベクトル`serializedState`をデシリアライズして、FMUステートのコピーを構築し、このコピーへのポインタである`FMUstate`を返します。
_[FMUstate`で`fmi2SetFMUState`を呼び出すと、この状態でシミュレーションが再開されます。]_

これらの関数は、FMUでのみサポートされています。
XMLファイルの<fmiModelDescription><ModelExchange / CoSimulation>`にあるオプションのケイパビリティフラグ`canGetAndSetFMUstate`および`canSerializeFMUstate`が明示的に`true`に設定されている場合、これらの関数はFMUでのみサポートされます（3.3.1項および4.3.1項を参照）。

==== 偏微分の取得

オプションとして、FMU の偏微分の評価を提供することが可能です。
モデル交換では、特定の時間の瞬間に偏微分を計算することを意味します。
コ・シミュレーションでは、特定の通信点での偏微分を計算することを意味する。
方向性のある微分を計算するための関数が1つ用意されています。
この関数は、必要な偏微分マトリクスを構築するために使用することができます。

[source, C]
----
fmi2Status fmi2GetDirectionalDerivative(fmi2Component c,
                      const fmi2ValueReference vUnknown_ref[], size_t nUnknown,
                      const fmi2ValueReference vKnown_ref[] , size_t nKnown,
                      const fmi2Real dvKnown[],
                            fmi2Real dvUnknown[])
----

[role=indented2]
この関数は、FMUの方向性デリバティブを計算します。
FMUには様々なモードがあり、各モードにおいてFMUは異なる方程式と異なる未知数で記述される可能性があります。
正確な定義は、モデル交換（3.1項）およびコ・シミュレーション（4.1項）の数学的な説明に記載されています。
どのモードでも、FMUの方程式の一般的な形式は次のとおりである。

[latexmath]
++++
\mathbf{v}_{unknown} = \mathbf{h}(\mathbf{v}_{known}, \mathbf{v}_{rest}),
++++

where

* latexmath:[\color{blue}{\mathbf{v}_{unknown}}] は、実際のModeで計算された未知のReal変数のベクトルです。

** _Initialization Mode_: <ModelStructure><InitialUnknowns>`に記載されている露出した未知数のうち、タイプがRealであるもの。

** _Continuous-Time Mode (ModelExchange)_: 連続時間の出力と状態導関数
(=`<ModelStructure><Outputs>`の下にリストアップされている変数で、タイプがReal、`variability = "continuous"`であり、`<ModelStructure><Derivatives>`の下に状態デリバティブとしてリストアップされている変数)。

** _Event Mode (ModelExchange)_: 連続時間モードと同じ変数に加えて、`<ModelStructure><Outputs>`の下に、タイプがRealで、`variability = "discrete"`の変数が追加されています。

** _Step Mode (CoSimulation)_: <ModelStructure><Outputs>` の下にリストされている変数で、タイプは Real で、`variability = continuous` または `discrete` です。
<ModelStructure><Derivatives>`が存在する場合、ここに記載されている変数も状態デリバティブとして表示されます。

* latexmath:[\color{blue}{\mathbf{v}_{known}}] は、実際のModeで値が変化する関数*h*のReal入力変数のベクトルです。
詳細は2.2.8項の要素`dependencies`の説明にあります。
_[例えば、連続時間モードでの連続時間の入力などです。
ScalarVariable`pass:[s]で`causality = "independent"`の変数が明示的に定義されている場合、この変数に対する方向性微分を計算することができます。
このような変数が定義されていない場合，独立変数に対する方向性微分は計算できません。]._

* latexmath:[\color{blue}{\mathbf{v}_{rest}}] は，関数*h*の入力変数のうち，実際のModeで値が変化するが非Real変数であるもの，あるいは，このModeでは値が変化しないが，他のModeでは値が変化するものの集合であり _[例えば、連続時間モードの離散時間入力]_

能力属性 `providesDirectionalDerivative` が `true` の場合、`fmi2GetDirectionalDerivative` は、選択された入力変数に対する *h* の偏微分の線形結合を計算します。 latexmath:[\color{blue}{\mathbf{v}_{known}}]:

[latexmath]
++++
\Delta \mathbf{v}_{unknown} = \frac{\delta \mathbf{h}}{\delta \mathbf{v}_{known}}\Delta \mathbf{v}_{known}
++++

それに伴い、方向性のある微分ベクトルを計算します。
latexmath:[\color{blue}{\Delta \mathbf{v}_{unknown}}] (`dvUnknown`) シードベクトルから
latexmath:[\color{blue}{\Delta \mathbf{v}_{known}}] (`dvKnown`)

_[変数の関係は、モードによって異なる。
例えば、連続時間モードでは、連続時間出力yは離散時間入力に依存しません（イベント間で一定に保たれているため）。
しかし、イベントモードでは、yは離散時間入力に依存する。]_ +
_この関数は、方程式系の疎密を考慮した数値微分によって方向性のある微分を計算してもよいし、（望ましい）解析的な微分によってもよい。_

_例:_ +
_FMUには次のような出力式があります。_

[latexmath]
++++
\begin{bmatrix}
y_1
\\
y_2
\end{bmatrix}
=
\begin{bmatrix}
g_1(x, u_1, u_3, u_4)
\\
g_2(x, u_1)
\end{bmatrix}
++++

_となり、このFMUは接続されているため、latexmath:[\color{blue}{y_1, u_1, u_3}]が代数的なループに現れます。
非線形ソルバーはヤコビアンを必要とし、このヤコビアンは、latexmath:[\color{blue}{y_1}]の偏導関数を用いて（数値微分せずに）計算することができます。
latexmath:[\color{blue}{u_1}] and latexmath:[\color{blue}{u_3}] が利用できます。
FMUが接続される環境に応じて、以下のようなデリバティブが提供されます。_

(a) _with one wrapper function around function fmi2GetDirectionalDerivative to compute the directional
derivatives with respect to these two variables (in other words, latexmath:[\color{blue}{v_{unknown} = y_1}],
latexmath:[\color{blue}{v_{known} = \left \{ u_1, u_3 \right \}}]), and then the environment calls
this wrapper function with latexmath:[\color{blue}{\Delta v_{known} = \left \{ 1, 0 \right \}}]
to compute the partial derivative with respect to
latexmath:[\color{blue}{u_1}] and latexmath:[\color{blue}{\Delta v_{known} = \left \{ 0, 1 \right \}}]
to compute the partial derivative with respect to latexmath:[\color{blue}{u_3}], or_

(a) _関数 fmi2GetDirectionalDerivative を中心としたラッパー関数で、この2つの変数に対する方向性のある微分を計算し（つまり、latexmath:[\color{blue}{v_{unknown} = y_1}]、latexmath:[\color{blue}{v_{known} = \left \{ u_1, u_3 \right \}}]）、このラッパー関数をlatexmath:[\color{blue}{\Delta v_{known} = \left \{ 1, 0 \right \}}]で呼び出す環境です。 環境はこのラッパー関数をlatexmath:[\color{blue}{u_1}]で呼び出し、latexmath:[\color{blue}{u_1}]とlatexmath:[\color{blue}{\Delta v_{known} = \left \{ 0, 1 \right \}}]に関する偏微分を計算します。 偏導関数を計算するには latexmath:[\color{blue}{u_3}]が必要です。_

(b) _と、fmi2GetDirectionalDerivativeの直接関数呼び出しが2回あります(言い換えれば、latexmath:[\color{blue}{v_{unknown} = y_1, v_{known} = u_1, \Delta v_{known} = 1}]と、latexmath:[\color{blue}{v_{unknown} = y_1, v_{known} = u_3, \Delta v_{known} = 1}]です)。_

_なお、この関数を解析的な導関数で直接実装すると:_

(a) _すべての入力変数に対して方向性のある微分を提供します。上の例では、 latexmath:[\color{blue}{\Delta y_1 = \frac{\delta g_1}{\delta x} \cdot \Delta x + \frac{\delta g_1}{\delta u_1} \cdot \Delta u_1 + \frac{\delta g_1}{\delta u_3} \cdot \Delta u_3 + \frac{\delta g_1}{\delta u_4} \cdot \Delta u_4}]_

(b) _全てのシード値を0に初期化します。上記の例では、latexmath:[\color{blue}{\Delta x = \Delta u_1 = \Delta u_3 = \Delta u_4 = 0}]となります。_

(c) _関数の引数で指定されたシード値を用いて、方向微分を計算します。上記の例では、以下のようになります。latexmath:[\color{blue}{\Delta v_{unknown} = \Delta y_1 (\Delta x = 0, \Delta u_1 = 1, \Delta u_3 = 1, \Delta u_4 = 0)}]]_

_[なお、関数fmi2GetDirectionalDerivativeは以下の目的で使用できます。:_

- _剛性法の数値積分には、行列 latexmath:[\color{blue}{\frac{\delta \mathbf{f}}{\delta \mathbf{x}}}]が必要です。_

- _FMUが他のFMUと接続されている場合、接続されているFMUのシステムのジャコビアンを計算するためには、連続した状態と入力に関する状態微分と出力の偏微分が必要となります。_

- _FMUを線形化する場合は、前項目と同様の微分が必要です。_

- _FMUを拡張カルマンフィルターのモデルとして使用した場合。
latexmath:[\color{blue}{\frac{\delta \mathbf{f}}{\delta \mathbf{x}}}]とlatexmath:[\color{blue}{\frac{\delta \mathbf{g}}{\delta \mathbf{x}}}]が必要です。_

_密な行列を計算する場合は、fmi2GetDirectionalDerivativeを連続して呼び出すことで、行列の列を簡単に構築できます。
例えば、システムのヤコビアンlatexmath:[\color{blue}{\mathbf{A} = \frac{\delta \mathbf{f}}{\delta \mathbf{x}}}]を密な行列として構築するには、以下のような方法があります。_

[source, C]
----
m = M_fmi2Instantiate("m", ...)  // "m" is the instance name
                                 // "M_" is the MODEL_IDENTIFIER
// from XML file
nx     = ...   // number of states
x_ref [..] = ...   // vector of value references of cont.-time states
xd_ref[..] = ...   // vector of value references of state derivatives
dvKnown[1] = {1.0}; //seed vector for fmi2GetDirectionalDerivative
...
// If required at this step, compute the Jacobian as dense matrix
   // Set time, states and inputs
   M_fmi2SetTime(m, time)
   M_fmi2SetContinuousStates(m, x, nx)
   M_fmi2SetReal/Integer/Boolean/String(m, ...)
   // Construct the Jacobian elements J[:,:] columnwise
for i in 1:nx loop
  M_fmi2GetDirectionalDerivative(m, xd_ref, nx, x_ref[i], 1, dvKnown, ci);
  J[:,i] = ci;    // ci is an auxiliary vector of nx elements
                  // (it holds the i-th column of the Jacobian)
end for;
----

_行列のスパース性を考慮しなければならない場合、その行列は次のようにして作られます。_

. _行列の入射情報（要素がゼロかゼロでないか）は、XMLファイルの要素<ModelStructure>から抽出されます。_

. _fmi2GetDirectionalDerivativeの1回の呼び出しで計算できる行列の列を決定するために、いわゆるグラフカラーリングアルゴリズムを採用しています。
効率的なグラフカラーリングアルゴリズムは、C/C++で書かれたライブラリColPack (https://cscapes.cs.purdue.edu/coloringpage/) (LGPL)や、Coleman, Garbow, Moréによるルーチン (Software for estimating sparse Jacobian matrices, ACM Transactions on Mathematical Software - TOMS , vol. 10, no. 3, pp. 346-347, 1984)など、自由に利用することができます。3, pp.346-347, 1984. http://www.netlib.org/toms/618 などを参照。_

. _(2)で決定した列に対して、fmi2DirectionalDerivativeの呼び出しが1回行われます。
それぞれの呼び出しの後、結果として得られる方向性のある微分ベクトルの要素は、偏微分行列の正しい位置にコピーされます。_

_詳細や実装上の注意点は(Akesson et.al. 2012)を参照してください]。_
